IO_CLASS Module Reference
Controls the input and output for the underlying postprocessor.
Data Types
interface INDEXING
interface READCOORD
interface READ_DIM
interface READ_GRID
interface READVALUE
interface WRITE_TEMPER
interface WRITE_PROG
interface READVEL
interface READVEL_BIN
type IO
Functions/Subroutines
subroutine read_dummy_sub (this, filename, dimen)
REAL(DP), dimension(:,:), pointer field_f (this)
REAL number_of_nodes_x_f (this)
REAL number_of_nodes_y_f (this)
REAL number_of_nodes_z_f (this)
Detailed Description
Controls the input and output for the underlying postprocessor.
Author
Felix Dietzsch
Function/Subroutine Documentation
REAL(DP),dimension(:,:),pointer IO_CLASS::field_f (CLASS(IO) this)
Definition at line 241 of file IO.f90.
Referenced by IO_CLASS::IO::field().
REAL IO_CLASS::number_of_nodes_x_f (CLASS(IO) this)
Definition at line 261 of file IO.f90.
Referenced by IO_CLASS::IO::NX().
REAL IO_CLASS::number_of_nodes_y_f (CLASS(IO) this)
Definition at line 267 of file IO.f90.
Referenced by IO_CLASS::IO::NY().
REAL IO_CLASS::number_of_nodes_z_f (CLASS(IO) this)
Definition at line 273 of file IO.f90.
Referenced by IO_CLASS::IO::NZ().
subroutine IO_CLASS::read_dummy_sub (CLASS(IO) this, CHARACTER(LEN=*),intent(in) filename, INTEGER(SP) dimen)
Definition at line 164 of file IO.f90.
Referenced by IO_CLASS::IO::read_file().