STATISTICS Module Reference
Provides functions for statistical computations.
Data Types
interface MEAN
interface CORREL
interface SHIFT
interface SPECTR
interface DEVIAT
Functions/Subroutines
subroutine SPEC2D (IN1, IN2, NX, NY, OUT)
Computes the three dimensional energy spectrum as the fourier transformation
 of the auto-correlation function. In the first step all three velocity
 components are fourier transformed. The second step consists of multiplying
 each transform with its conjugate complex in order to get the elements of the
 main diagonal of the velocity spectrum tensor
\hat{R}_{ii}\left(\kappa,t\right)= \left<\hat{u}_i^{*}\left(\kappa,t\right)\,\hat{u}_i\left(\kappa,t\right)\right>= \Phi_{ii}\left(\kappa,t\right).
 After the components of $\Phi$ have been determined an integration over
 spherical shells has to be computed in order to get the three dimensional
 velocity spectrum.
 E(k)=\oint\frac{1}{2}\Phi_{ii}(\kappa)\,d\mathrm{S}(\kappa) 
subroutine SPEC3D (PROCNUM, IN1, IN2, IN3, NX, NY, NZ, OUT)
Computes the three dimensional energy spectrum as the fourier transformation
 of the auto-correlation function. In the first step all three velocity
 components are fourier transformed. The second step consists of multiplying
 each transform with its conjugate complex in order to get the elements of the
 main diagonal of the velocity spectrum tensor
\hat{R}_{ii}\left(\kappa,t\right)= \left<\hat{u}_i^{*}\left(\kappa,t\right)\,\hat{u}_i\left(\kappa,t\right)\right>= \Phi_{ii}\left(\kappa,t\right).
 After the components of $\Phi$ have been determined an integration over
 spherical shells has to be computed in order to get the three dimensional
 velocity spectrum.
 E(k)=\oint\frac{1}{2}\Phi_{ii}(\kappa)\,d\mathrm{S}(\kappa) 
subroutine DEVIATION (VELO, NX, NY, NZ, SIGMA)
Computes the standard deviation of the 3D input array. It is computed according to
\sigma = \sqrt{\frac{1}{N} \sum_{i=1}^N (x_i - \mu)^2}, {\rm \ \ where\ \ } \mu = \frac{1}{N} \sum_{i=1}^N x_i. 
subroutine FFTSHIFT (IN, NX, NY)
Shifts the input array towards the zero frequencies.
subroutine CORREL3D (IN, NX, NY, NZ, OUT)
Computes the auto-correlation coefficients of the 3D input array. The general definition of the auto-correlation (often exressed as the covariance) function is
\mathrm{cov}(f,f)=\left(f\star f\right)(r)=\int_0^{\infty}f(x)\,f(x+r)\,dx 
 One important feature of the correlation function is that is satisfies
\mathcal{F}\{f\star f\}=(\mathcal{F}\{f\})^*\cdot\mathcal{F}\{f\}. 
 In the code this allows for fast computations of the correlation function using the FFT approach. In order to get the correlation coefficients, the previously mentioned function has to be devided by standard deviations of the input arrays.
r=\frac{\mathrm{cov}(f,f)}{\sigma_f\,\sigma_f} 
subroutine XCORREL (IN1, IN2, NX, NY, NZ, OUT)
Computes the cross-correlation coefficients of the 3D input arrays. The general definition of the cross-correlation (often exressed as the covariance) function is
\mathrm{cov}(f,g)=\left(f\star g\right)(r)=\int_0^{\infty}f(x)\,g(x+r)\,dx 
 One important feature of the correlation function is that is satisfies
\mathcal{F}\{f\star g\}=(\mathcal{F}\{f\})^*\cdot\mathcal{F}\{g\}. 
 In the code this allows for fast computations of the correlation function using the FFT approach. In order to get the correlation coefficients, the previously mentioned function has to be devided by standard deviations of the input arrays.
r=\frac{\mathrm{cov}(f,g)}{\sigma_f\,\sigma_g} 
 Computes the cross-correlation of the 3D input array
subroutine MEAN1D (M, NX)
subroutine MEAN3D (M, NX, NY, NZ, MEAN)
Shifts the input array towards the zero frequencies.
subroutine MEAN4D (M, NX, NY, NZ, DIM, MEAN)
Detailed Description
Provides functions for statistical computations.
Author
Felix Dietzsch
Function/Subroutine Documentation
subroutine STATISTICS::CORREL3D (COMPLEX(DPC),dimension(:,:,:),intent(in) IN, INTEGER(SP) NX, INTEGER(SP) NY, INTEGER(SP) NZ, COMPLEX(DPC),dimension(:,:,:),intent(inout) OUT)
Computes the auto-correlation coefficients of the 3D input array. The general definition of the auto-correlation (often exressed as the covariance) function is
\mathrm{cov}(f,f)=\left(f\star f\right)(r)=\int_0^{\infty}f(x)\,f(x+r)\,dx 
 One important feature of the correlation function is that is satisfies
\mathcal{F}\{f\star f\}=(\mathcal{F}\{f\})^*\cdot\mathcal{F}\{f\}. 
 In the code this allows for fast computations of the correlation function using the FFT approach. In order to get the correlation coefficients, the previously mentioned function has to be devided by standard deviations of the input arrays.
r=\frac{\mathrm{cov}(f,f)}{\sigma_f\,\sigma_f} 
Author
Felix Dietzsch Computes the auto-correlation coefficients of the 3D input array
Parameters
in IN 3D array for the computation of the 3D auto-correlation coefficients
in NX Number of nodes in x direction
in NY Number of nodes in y direction
in NZ Number of nodes in z direction
out OUT 3D array of auto-correlation coeffcients
Definition at line 416 of file STATISTICS.f90.
References DEVIATION().
subroutine STATISTICS::DEVIATION (REAL(DP),dimension(:,:,:) VELO, INTEGER(SP) NX, INTEGER(SP) NY, NZ, REAL(DP) SIGMA)
Computes the standard deviation of the 3D input array. It is computed according to
\sigma = \sqrt{\frac{1}{N} \sum_{i=1}^N (x_i - \mu)^2}, {\rm \ \ where\ \ } \mu = \frac{1}{N} \sum_{i=1}^N x_i. 
Author
Felix Dietzsch Computes the standard deviation of the 3D input array.
Parameters
in VELO 3D array of which the deviation is to be computed
in NX Number of nodes in x direction
in NY Number of nodes in y direction
in NZ Number of nodes in z direction
out SIGMA Standard deviation of the input array velocities
Definition at line 319 of file STATISTICS.f90.
References MEAN3D().
Referenced by CORREL3D(), and XCORREL().
subroutine STATISTICS::FFTSHIFT (COMPLEX(DPC),dimension(nx,ny),intent(inout) IN, INTEGER(SP) NX, INTEGER(SP) NY)
Shifts the input array towards the zero frequencies.
Author
Felix Dietzsch Shifts the input array towards the zero frequencies.
Parameters
in IN 2D array of shifted frequencies
in NX Number of nodes in y direction
in NY Number of nodes in z direction
out IN 2D array of shifted frequencies
Definition at line 362 of file STATISTICS.f90.
subroutine STATISTICS::MEAN1D (REAL(DP),dimension(:) M, INTEGER(SP) NX)
Definition at line 526 of file STATISTICS.f90.
subroutine STATISTICS::MEAN3D (REAL(DP),dimension(:,:,:) M, INTEGER(SP) NX, INTEGER(SP) NY, NZ, REAL(DP) MEAN)
Shifts the input array towards the zero frequencies.
Author
Felix Dietzsch
Parameters
in M 3D array for the computation of the mean value
in NX Number of nodes in x direction
in NY Number of nodes in y direction
in NZ Number of nodes in z direction
out MEAN Computed mean value
Definition at line 547 of file STATISTICS.f90.
Referenced by DEVIATION().
subroutine STATISTICS::MEAN4D (REAL(DP),dimension(:,:,:,:) M, INTEGER(SP) NX, INTEGER(SP) NY, NZ, INTEGER(SP) DIM, REAL(DP) MEAN)
Definition at line 556 of file STATISTICS.f90.
subroutine STATISTICS::SPEC2D (REAL(DP),dimension(:,:,:) IN1, REAL(DP),dimension(:,:,:) IN2, INTEGER(SP) NX, INTEGER(SP) NY, COMPLEX(DPC),dimension(:),intent(inout) OUT)
Computes the three dimensional energy spectrum as the fourier transformation
 of the auto-correlation function. In the first step all three velocity
 components are fourier transformed. The second step consists of multiplying
 each transform with its conjugate complex in order to get the elements of the
 main diagonal of the velocity spectrum tensor
\hat{R}_{ii}\left(\kappa,t\right)= \left<\hat{u}_i^{*}\left(\kappa,t\right)\,\hat{u}_i\left(\kappa,t\right)\right>= \Phi_{ii}\left(\kappa,t\right).
 After the components of $\Phi$ have been determined an integration over
 spherical shells has to be computed in order to get the three dimensional
 velocity spectrum.
 E(k)=\oint\frac{1}{2}\Phi_{ii}(\kappa)\,d\mathrm{S}(\kappa) 
Author
Felix Dietzsch Computes the two dimensional spectrum
Parameters
in IN1 3D array of first velocity component
in IN2 3D array of second velocity component
in NX Number of nodes in x direction
in NY Number of nodes in y direction
out OUT Vector containing the spectrum for the input velocities
Definition at line 64 of file STATISTICS.f90.
subroutine STATISTICS::SPEC3D (INTEGER(SP) PROCNUM, REAL(DP),dimension(:,:,:) IN1, REAL(DP),dimension(:,:,:) IN2, REAL(DP),dimension(:,:,:) IN3, INTEGER(SP) NX, INTEGER(SP) NY, INTEGER(SP) NZ, COMPLEX(DPC),dimension(:),intent(inout) OUT)
Computes the three dimensional energy spectrum as the fourier transformation
 of the auto-correlation function. In the first step all three velocity
 components are fourier transformed. The second step consists of multiplying
 each transform with its conjugate complex in order to get the elements of the
 main diagonal of the velocity spectrum tensor
\hat{R}_{ii}\left(\kappa,t\right)= \left<\hat{u}_i^{*}\left(\kappa,t\right)\,\hat{u}_i\left(\kappa,t\right)\right>= \Phi_{ii}\left(\kappa,t\right).
 After the components of $\Phi$ have been determined an integration over
 spherical shells has to be computed in order to get the three dimensional
 velocity spectrum.
 E(k)=\oint\frac{1}{2}\Phi_{ii}(\kappa)\,d\mathrm{S}(\kappa) 
Author
Felix Dietzsch Computes the three dimensional spectrum
Parameters
in IN1 3D array of first velocity component
in IN2 3D array of second velocity component
in IN3 3D array of third velocity component
in NX Number of nodes in x direction
in NY Number of nodes in y direction
in NZ Number of nodes in z direction
out Vector containing the spectrum for the input velocities
Todo Implementation of the 3D spectrum computation
 eMail from Michael Gauding from July 12th 2011
 concerns the integration of spherical shells
Definition at line 156 of file STATISTICS.f90.
subroutine STATISTICS::XCORREL (COMPLEX(DPC),dimension(:,:,:),intent(in) IN1, COMPLEX(DPC),dimension(:,:,:),intent(in) IN2, INTEGER(SP) NX, INTEGER(SP) NY, INTEGER(SP) NZ, COMPLEX(DPC),dimension(:,:,:),intent(inout) OUT)
Computes the cross-correlation coefficients of the 3D input arrays. The general definition of the cross-correlation (often exressed as the covariance) function is
\mathrm{cov}(f,g)=\left(f\star g\right)(r)=\int_0^{\infty}f(x)\,g(x+r)\,dx 
 One important feature of the correlation function is that is satisfies
\mathcal{F}\{f\star g\}=(\mathcal{F}\{f\})^*\cdot\mathcal{F}\{g\}. 
 In the code this allows for fast computations of the correlation function using the FFT approach. In order to get the correlation coefficients, the previously mentioned function has to be devided by standard deviations of the input arrays.
r=\frac{\mathrm{cov}(f,g)}{\sigma_f\,\sigma_g} 
 Computes the cross-correlation of the 3D input array
Author
Felix Dietzsch
Parameters
in IN1 3D array for the computation of the 3D cross-correlation coefficients
in IN2 3D array for the computation of the 3D cross-correlation coefficients
in NX Number of nodes in x direction
in NY Number of nodes in y direction
in NZ Number of nodes in z direction
out OUT 3D array of cross-correlation coeffcients
Definition at line 485 of file STATISTICS.f90.
References DEVIATION().