IO_CLASS::IO Type Reference
Public Member Functions
PROCEDURE, public file_stats => read_file_sub
PROCEDURE, public NOL => number_of_lines_f
PROCEDURE, public NON => number_of_nodes_f
PROCEDURE, public NX => number_of_nodes_x_f
PROCEDURE, public NY => number_of_nodes_y_f
PROCEDURE, public NZ => number_of_nodes_z_f
PROCEDURE, public read_file => read_dummy_sub
PROCEDURE, public field => field_f
Public Attributes
INTEGER(SP) NOLINES
INTEGER(SP) NONODES
INTEGER(SP) NONX
INTEGER(SP) NONY
INTEGER(SP) NONZ
INTEGER(SP) DIM
REAL(DP), dimension(:,:), pointer dummy
Detailed Description
Definition at line 142 of file IO.f90.
Member Function/Subroutine Documentation
PROCEDURE,public IO_CLASS::IO::field ()
Definition at line 159 of file IO.f90.
References IO_CLASS::field_f().
PROCEDURE,public IO_CLASS::IO::file_stats ()
Definition at line 152 of file IO.f90.
PROCEDURE,public IO_CLASS::IO::NOL ()
Definition at line 153 of file IO.f90.
PROCEDURE,public IO_CLASS::IO::NON ()
Definition at line 154 of file IO.f90.
PROCEDURE,public IO_CLASS::IO::NX ()
Definition at line 155 of file IO.f90.
References IO_CLASS::number_of_nodes_x_f().
PROCEDURE,public IO_CLASS::IO::NY ()
Definition at line 156 of file IO.f90.
References IO_CLASS::number_of_nodes_y_f().
PROCEDURE,public IO_CLASS::IO::NZ ()
Definition at line 157 of file IO.f90.
References IO_CLASS::number_of_nodes_z_f().
PROCEDURE,public IO_CLASS::IO::read_file ()
Definition at line 158 of file IO.f90.
References IO_CLASS::read_dummy_sub().
Member Data Documentation
INTEGER(SP) IO_CLASS::IO::DIM
Definition at line 149 of file IO.f90.
REAL(DP),dimension(:,:),pointer IO_CLASS::IO::dummy
Definition at line 150 of file IO.f90.
INTEGER(SP) IO_CLASS::IO::NOLINES
Definition at line 144 of file IO.f90.
INTEGER(SP) IO_CLASS::IO::NONODES
Definition at line 145 of file IO.f90.
INTEGER(SP) IO_CLASS::IO::NONX
Definition at line 146 of file IO.f90.
INTEGER(SP) IO_CLASS::IO::NONY
Definition at line 147 of file IO.f90.
INTEGER(SP) IO_CLASS::IO::NONZ
Definition at line 148 of file IO.f90.
The documentation for this type was generated from the following file:
/home/fdietzsc/fortran/POSTPROC/SOURCES/IO.f90